-- MySQL Script generated by MySQL Workbench
-- Tue Jun  9 09:32:07 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema catastro_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `catastro_db` ;

-- -----------------------------------------------------
-- Schema catastro_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `catastro_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci ;
USE `catastro_db` ;

-- -----------------------------------------------------
-- Table `catastro_db`.`c1m_region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`c1m_region` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`c1m_region` (
  `RegCod` INT NOT NULL AUTO_INCREMENT COMMENT 'Código Región – PK (N,2)',
  `RegNom` VARCHAR(60) NOT NULL COMMENT 'Nombre oficial (A,60)',
  `RegEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`RegCod`),
  INDEX `IDX_REG_nom` (`RegNom` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Maestro Región – UBIGEO N1';


-- -----------------------------------------------------
-- Table `catastro_db`.`c1m_provincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`c1m_provincia` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`c1m_provincia` (
  `ProCod` INT NOT NULL COMMENT 'Código Provincia – PK (N,4)',
  `ProReg` INT NOT NULL COMMENT 'Región [FK → C1M_REGION]',
  `ProNom` VARCHAR(60) NOT NULL COMMENT 'Nombre oficial (A,60)',
  `ProEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`ProCod`),
  INDEX `IDX_PRO_reg` (`ProReg` ASC) VISIBLE,
  INDEX `IDX_PRO_nom` (`ProNom` ASC) VISIBLE,
  CONSTRAINT `FK_PRO_REG`
    FOREIGN KEY (`ProReg`)
    REFERENCES `catastro_db`.`c1m_region` (`RegCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Maestro Provincia – UBIGEO N2';


-- -----------------------------------------------------
-- Table `catastro_db`.`c1m_distrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`c1m_distrito` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`c1m_distrito` (
  `DisCod` INT NOT NULL COMMENT 'Código Distrito – PK (N,6)',
  `DisPro` INT NOT NULL COMMENT 'Provincia [FK → C1M_PROVINCIA]',
  `DisNom` VARCHAR(60) NOT NULL COMMENT 'Nombre oficial (A,60)',
  `DisEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`DisCod`),
  INDEX `IDX_DIS_pro` (`DisPro` ASC) VISIBLE,
  INDEX `IDX_DIS_nom` (`DisNom` ASC) VISIBLE,
  CONSTRAINT `FK_DIS_PRO`
    FOREIGN KEY (`DisPro`)
    REFERENCES `catastro_db`.`c1m_provincia` (`ProCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Maestro Distrito – UBIGEO N3';


-- -----------------------------------------------------
-- Table `catastro_db`.`c1m_municipalidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`c1m_municipalidad` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`c1m_municipalidad` (
  `MunCod` INT NOT NULL AUTO_INCREMENT COMMENT 'Código Municipalidad – PK (N,6)',
  `MunDis` INT NOT NULL COMMENT 'Distrito [FK → C1M_DISTRITO] – UBIGEO N4',
  `MunNom` VARCHAR(60) NOT NULL COMMENT 'Nombre oficial (A,60)',
  `MunAlcNom` VARCHAR(120) NULL DEFAULT NULL COMMENT 'Nombre del Alcalde (A,120)',
  `MunCor` VARCHAR(80) NULL DEFAULT NULL COMMENT 'Correo electrónico (A,80)',
  `MunTelCon` VARCHAR(15) NULL DEFAULT NULL COMMENT 'Teléfono de contacto (A,15)',
  `MunEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`MunCod`),
  INDEX `IDX_MUN_dis` (`MunDis` ASC) VISIBLE,
  INDEX `IDX_MUN_nom` (`MunNom` ASC) VISIBLE,
  CONSTRAINT `FK_MUN_DIS`
    FOREIGN KEY (`MunDis`)
    REFERENCES `catastro_db`.`c1m_distrito` (`DisCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Maestro Municipalidad – UBIGEO N4 (depende del Distrito)';


-- -----------------------------------------------------
-- Table `catastro_db`.`c2m_zona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`c2m_zona` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`c2m_zona` (
  `ZonCod` INT NOT NULL AUTO_INCREMENT COMMENT 'Código Zona – PK (N,6)',
  `ZonMun` INT NOT NULL COMMENT 'Municipalidad [FK → C1M_MUNICIPALIDAD]',
  `ZonNom` VARCHAR(60) NOT NULL COMMENT 'Nombre zona – único por municipio (A,60)',
  `ZonDes` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Descripción (A,100)',
  `ZonTip` CHAR(1) NOT NULL COMMENT 'Tipo [U=Urbana R=Rural] (A,1)',
  `ZonSupKm2` DECIMAL(10,2) NULL DEFAULT NULL COMMENT 'Superficie km² (N,8,2)',
  `ZonEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`ZonCod`),
  UNIQUE INDEX `UQ_ZON_NOM_MUN` (`ZonMun` ASC, `ZonNom` ASC) VISIBLE,
  INDEX `IDX_ZON_mun` (`ZonMun` ASC) VISIBLE,
  INDEX `IDX_ZON_tip` (`ZonTip` ASC) VISIBLE,
  CONSTRAINT `FK_ZON_MUN`
    FOREIGN KEY (`ZonMun`)
    REFERENCES `catastro_db`.`c1m_municipalidad` (`MunCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Maestro Zonas – UBIGEO N5';


-- -----------------------------------------------------
-- Table `catastro_db`.`c3m_via_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`c3m_via_tipo` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`c3m_via_tipo` (
  `VtCod` VARCHAR(4) NOT NULL COMMENT 'Código tipo vía – PK (A,4) Ej: AV JR CA',
  `VtNom` VARCHAR(40) NOT NULL COMMENT 'Nombre completo Ej: Avenida Jirón (A,40)',
  `VtEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`VtCod`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Catálogo Tipo de Vía – nomenclatura SUNARP/MTC';


-- -----------------------------------------------------
-- Table `catastro_db`.`c3m_direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`c3m_direccion` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`c3m_direccion` (
  `DirCod` INT NOT NULL AUTO_INCREMENT COMMENT 'Código Dirección – PK (N,8)',
  `DirZon` INT NOT NULL COMMENT 'Zona [FK → C2M_ZONA]',
  `DirViaTip` VARCHAR(4) NOT NULL COMMENT 'Tipo vía [FK → C3M_VIA_TIPO] Ej: AV JR CA',
  `DirViaNom` VARCHAR(80) NOT NULL COMMENT 'Nombre de la vía Ej: Lima Puno (A,80)',
  `DirNum` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Número de fachada Ej: 123 S/N (A,10)',
  `DirInt` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Interior/Dpto/Piso Ej: 101 (A,10)',
  `DirUrb` VARCHAR(80) NULL DEFAULT NULL COMMENT 'Urbanización Barrio o AA.HH. (A,80)',
  `DirRef` VARCHAR(120) NULL DEFAULT NULL COMMENT 'Referencia libre Ej: frente al parque (A,120)',
  `DirCodPos` VARCHAR(5) NULL DEFAULT NULL COMMENT 'Código Postal SERPOST 5 dígitos (A,5)',
  `DirLat` DECIMAL(10,7) NULL DEFAULT NULL COMMENT 'Latitud GPS decimal Ej: -16.3988 (N,10,7)',
  `DirLon` DECIMAL(10,7) NULL DEFAULT NULL COMMENT 'Longitud GPS decimal Ej: -71.5369 (N,10,7)',
  `DirEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`DirCod`),
  INDEX `FK_DIR_VIATIP` (`DirViaTip` ASC) VISIBLE,
  INDEX `IDX_DIR_zon` (`DirZon` ASC) VISIBLE,
  INDEX `IDX_DIR_vnom` (`DirViaNom` ASC) VISIBLE,
  INDEX `IDX_DIR_codpos` (`DirCodPos` ASC) VISIBLE,
  INDEX `IDX_DIR_geo` (`DirLat` ASC, `DirLon` ASC) VISIBLE,
  CONSTRAINT `FK_DIR_VIATIP`
    FOREIGN KEY (`DirViaTip`)
    REFERENCES `catastro_db`.`c3m_via_tipo` (`VtCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_DIR_ZON`
    FOREIGN KEY (`DirZon`)
    REFERENCES `catastro_db`.`c2m_zona` (`ZonCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Dirección Normalizada – estilo formulario SUNARP';


-- -----------------------------------------------------
-- Table `catastro_db`.`c5m_tipo_predio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`c5m_tipo_predio` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`c5m_tipo_predio` (
  `TipPrCod` VARCHAR(4) NOT NULL COMMENT 'Código – PK (A,4) Ej: TP01',
  `TipPrNom` VARCHAR(60) NOT NULL COMMENT 'Nombre  Ej: Residencial (A,60)',
  `TipPrDes` VARCHAR(200) NULL DEFAULT NULL COMMENT 'Descripción del tipo (A,200)',
  `TipPrEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro [1=Activo 0=Inactivo]',
  PRIMARY KEY (`TipPrCod`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Catálogo Tipo de Predio';


-- -----------------------------------------------------
-- Table `catastro_db`.`c5m_uso_predio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`c5m_uso_predio` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`c5m_uso_predio` (
  `UsoPrCod` VARCHAR(4) NOT NULL COMMENT 'Código – PK (A,4) Ej: UP01',
  `UsoPrNom` VARCHAR(60) NOT NULL COMMENT 'Nombre  Ej: Habitacional (A,60)',
  `UsoPrDes` VARCHAR(200) NULL DEFAULT NULL COMMENT 'Descripción del uso (A,200)',
  `UsoPrEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`UsoPrCod`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Catálogo Uso de Predio';


-- -----------------------------------------------------
-- Table `catastro_db`.`c3m_vivienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`c3m_vivienda` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`c3m_vivienda` (
  `VivCod` VARCHAR(10) NOT NULL COMMENT 'Código Predio – PK (A,10)',
  `VivZon` INT NOT NULL COMMENT 'Zona [FK → C2M_ZONA]',
  `VivDir` INT NULL DEFAULT NULL COMMENT 'Dirección [FK → C3M_DIRECCION] NULL=sin asignar',
  `VivUbigeo` VARCHAR(15) NULL DEFAULT NULL COMMENT 'Código INEI/UBIGEO externo Ej: 060101-0001 (A,15)',
  `VivTipPr` VARCHAR(4) NULL DEFAULT NULL COMMENT 'Tipo Predio [FK → C5M_TIPO_PREDIO] NULL=sin clasificar',
  `VivUsoPr` VARCHAR(4) NULL DEFAULT NULL COMMENT 'Uso Predio [FK → C5M_USO_PREDIO] NULL=sin clasificar',
  `VivVal` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Valor declarativo del predio S/ (N,10,2)',
  `VivEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`VivCod`),
  INDEX `IDX_VIV_zon` (`VivZon` ASC) VISIBLE,
  INDEX `IDX_VIV_dir` (`VivDir` ASC) VISIBLE,
  INDEX `IDX_VIV_ubigeo` (`VivUbigeo` ASC) VISIBLE,
  INDEX `IDX_VIV_tippr` (`VivTipPr` ASC) VISIBLE,
  INDEX `IDX_VIV_usopr` (`VivUsoPr` ASC) VISIBLE,
  INDEX `IDX_VIV_est` (`VivEstReg` ASC) VISIBLE,
  CONSTRAINT `FK_VIV_DIR`
    FOREIGN KEY (`VivDir`)
    REFERENCES `catastro_db`.`c3m_direccion` (`DirCod`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_VIV_TIPPR`
    FOREIGN KEY (`VivTipPr`)
    REFERENCES `catastro_db`.`c5m_tipo_predio` (`TipPrCod`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_VIV_USOPR`
    FOREIGN KEY (`VivUsoPr`)
    REFERENCES `catastro_db`.`c5m_uso_predio` (`UsoPrCod`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_VIV_ZON`
    FOREIGN KEY (`VivZon`)
    REFERENCES `catastro_db`.`c2m_zona` (`ZonCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Maestro Vivienda/Predio – UBIGEO N6 con FK a dirección normalizada';


-- -----------------------------------------------------
-- Table `catastro_db`.`c3m_bloque_casas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`c3m_bloque_casas` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`c3m_bloque_casas` (
  `BloVivCod` VARCHAR(10) NOT NULL COMMENT 'PK/FK → C3M_VIVIENDA (herencia)',
  `BloMetB` DECIMAL(8,2) NOT NULL COMMENT 'm² totales del bloque (>0)',
  `BloOd` VARCHAR(200) NULL DEFAULT NULL COMMENT 'Datos adicionales (A,200)',
  `BloEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`BloVivCod`),
  CONSTRAINT `FK_BLO_VIV`
    FOREIGN KEY (`BloVivCod`)
    REFERENCES `catastro_db`.`c3m_vivienda` (`VivCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Subtipo Vivienda – Bloque de Casas (edificio de pisos)';


-- -----------------------------------------------------
-- Table `catastro_db`.`c3m_casa_particular`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`c3m_casa_particular` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`c3m_casa_particular` (
  `CasVivCod` VARCHAR(10) NOT NULL COMMENT 'PK/FK → C3M_VIVIENDA (herencia)',
  `CasMetC` DECIMAL(8,2) NOT NULL COMMENT 'm² construidos (>0)',
  `CasOd` VARCHAR(200) NULL DEFAULT NULL COMMENT 'Datos adicionales (A,200)',
  `CasEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`CasVivCod`),
  CONSTRAINT `FK_CAS_VIV`
    FOREIGN KEY (`CasVivCod`)
    REFERENCES `catastro_db`.`c3m_vivienda` (`VivCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Subtipo Vivienda – Casa Particular unifamiliar';


-- -----------------------------------------------------
-- Table `catastro_db`.`c3m_partida_registral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`c3m_partida_registral` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`c3m_partida_registral` (
  `PrtCod` INT NOT NULL AUTO_INCREMENT COMMENT 'Código interno – PK (N,8)',
  `PrtViv` VARCHAR(10) NOT NULL COMMENT 'Predio [FK → C3M_VIVIENDA]',
  `PrtZonReg` VARCHAR(6) NOT NULL COMMENT 'Zona Registral SUNARP Ej: ZR-XII (A,6)',
  `PrtNumPartida` VARCHAR(12) NOT NULL COMMENT 'Número de Partida Ej: 11012345 (A,12)',
  `PrtFolioTomo` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Tomo formato antiguo Ej: T-001 (A,10)',
  `PrtFolioFolio` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Folio formato antiguo Ej: F-123 (A,10)',
  `PrtAsiento` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Asiento de inscripción Ej: C00001 (A,10)',
  `PrtTipoActo` VARCHAR(40) NOT NULL COMMENT 'Tipo de acto Ej: Compraventa Hipoteca (A,40)',
  `PrtPropNom` VARCHAR(200) NULL DEFAULT NULL COMMENT 'Nombre propietario en partida SUNARP (A,200)',
  `PrtPropDNI` VARCHAR(12) NULL DEFAULT NULL COMMENT 'DNI o RUC del propietario en partida (A,12)',
  `PrtEst` CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'Estado: A=Activa C=Cerrada D=Duplicada N=Nula',
  `PrtFecIns` DATE NOT NULL COMMENT 'Fecha de inscripción en SUNARP',
  `PrtFecUltAct` DATE NULL DEFAULT NULL COMMENT 'Fecha de última actualización',
  `PrtAreaM2` DECIMAL(10,2) NULL DEFAULT NULL COMMENT 'Área del predio según partida SUNARP m² (>0)',
  `PrtObs` VARCHAR(200) NULL DEFAULT NULL COMMENT 'Observaciones (A,200)',
  `PrtEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`PrtCod`),
  UNIQUE INDEX `UQ_PRT_ZON_PAR_ASI` (`PrtZonReg` ASC, `PrtNumPartida` ASC, `PrtAsiento` ASC) VISIBLE,
  INDEX `IDX_PRT_viv` (`PrtViv` ASC) VISIBLE,
  INDEX `IDX_PRT_partida` (`PrtNumPartida` ASC) VISIBLE,
  INDEX `IDX_PRT_zonreg` (`PrtZonReg` ASC) VISIBLE,
  INDEX `IDX_PRT_activa` (`PrtViv` ASC, `PrtEst` ASC) VISIBLE,
  CONSTRAINT `FK_PRT_VIV`
    FOREIGN KEY (`PrtViv`)
    REFERENCES `catastro_db`.`c3m_vivienda` (`VivCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Partida Registral SUNARP – inscripción del predio en Registros Públicos';


-- -----------------------------------------------------
-- Table `catastro_db`.`c4m_departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`c4m_departamento` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`c4m_departamento` (
  `DepBloCod` VARCHAR(10) NOT NULL COMMENT 'Bloque [FK → C3M_BLOQUE_CASAS] (PK1)',
  `DepEsc` VARCHAR(4) NOT NULL COMMENT 'Escalera (PK2)',
  `DepNiv` TINYINT NOT NULL DEFAULT '0' COMMENT 'Piso/Nivel (PK3) 0=planta baja',
  `DepPue` VARCHAR(4) NOT NULL COMMENT 'Puerta/Número (PK4)',
  `DepMetP` DECIMAL(6,2) NOT NULL COMMENT 'm² del departamento (>0)',
  `DepOd` VARCHAR(200) NULL DEFAULT NULL COMMENT 'Datos adicionales (A,200)',
  `DepEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`DepBloCod`, `DepEsc`, `DepNiv`, `DepPue`),
  INDEX `IDX_DEP_bloque` (`DepBloCod` ASC) VISIBLE,
  CONSTRAINT `FK_DEP_BLO`
    FOREIGN KEY (`DepBloCod`)
    REFERENCES `catastro_db`.`c3m_bloque_casas` (`BloVivCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Entidad débil – Departamento/Piso dentro de un Bloque de Casas';


-- -----------------------------------------------------
-- Table `catastro_db`.`c5m_valor_catastral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`c5m_valor_catastral` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`c5m_valor_catastral` (
  `ValCod` INT NOT NULL AUTO_INCREMENT COMMENT 'Código Valoración – PK (N,8)',
  `ValViv` VARCHAR(10) NOT NULL COMMENT 'Predio [FK → C3M_VIVIENDA]',
  `ValAnio` YEAR NOT NULL COMMENT 'Año de valoración (>2000)',
  `ValMon` DECIMAL(14,2) NOT NULL COMMENT 'Valor catastral S/ (>0)',
  `ValFecReg` DATE NOT NULL COMMENT 'Fecha de registro',
  `ValFecMod` DATE NULL DEFAULT NULL COMMENT 'Fecha de modificación',
  `ValEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`ValCod`),
  UNIQUE INDEX `UQ_VAL_VIV_ANIO` (`ValViv` ASC, `ValAnio` ASC) VISIBLE,
  INDEX `IDX_VAL_viv` (`ValViv` ASC) VISIBLE,
  INDEX `IDX_VAL_anio` (`ValAnio` ASC) VISIBLE,
  INDEX `IDX_VAL_act` (`ValViv` ASC, `ValAnio` ASC, `ValEstReg` ASC) VISIBLE,
  CONSTRAINT `FK_VAL_VIV`
    FOREIGN KEY (`ValViv`)
    REFERENCES `catastro_db`.`c3m_vivienda` (`VivCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Valor Catastral – valoración económica anual del predio';


-- -----------------------------------------------------
-- Table `catastro_db`.`h6m_persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`h6m_persona` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`h6m_persona` (
  `PerDNI` INT NOT NULL COMMENT 'DNI Persona – PK (N,8)',
  `PerNom` VARCHAR(60) NOT NULL COMMENT 'Nombres (A,60)',
  `PerApePat` VARCHAR(60) NOT NULL COMMENT 'Apellido paterno (A,60)',
  `PerApeMat` VARCHAR(60) NOT NULL COMMENT 'Apellido materno (A,60)',
  `PerIng` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Ingresos mensuales S/ (>=0)',
  `PerViv` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Vivienda habitual [FK → C3M_VIVIENDA] NULL=sin asignar',
  `PerEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro [0=fallecido]',
  PRIMARY KEY (`PerDNI`),
  INDEX `IDX_PER_viv` (`PerViv` ASC) VISIBLE,
  INDEX `IDX_PER_ape` (`PerApePat` ASC, `PerApeMat` ASC) VISIBLE,
  INDEX `IDX_PER_nom` (`PerApePat` ASC, `PerApeMat` ASC, `PerNom` ASC) VISIBLE,
  CONSTRAINT `FK_PER_VIV`
    FOREIGN KEY (`PerViv`)
    REFERENCES `catastro_db`.`c3m_vivienda` (`VivCod`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Maestro Persona – PerViv nullable para carga masiva independiente';


-- -----------------------------------------------------
-- Table `catastro_db`.`h6m_cab_familia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`h6m_cab_familia` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`h6m_cab_familia` (
  `CabDNI` INT NOT NULL COMMENT 'DNI Cabeza de Familia [FK → H6M_PERSONA] (PK1)',
  `MieDNI` INT NOT NULL COMMENT 'DNI Miembro [FK → H6M_PERSONA] (PK2)',
  `CabFecIni` DATE NOT NULL COMMENT 'Fecha inicio en el grupo familiar',
  `CabFecFin` DATE NULL DEFAULT NULL COMMENT 'Fecha fin – NULL si sigue activo',
  `CabEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`CabDNI`, `MieDNI`),
  INDEX `IDX_CAB_miembro` (`MieDNI` ASC) VISIBLE,
  CONSTRAINT `FK_CAB_CABEZA`
    FOREIGN KEY (`CabDNI`)
    REFERENCES `catastro_db`.`h6m_persona` (`PerDNI`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_CAB_MIEMBRO`
    FOREIGN KEY (`MieDNI`)
    REFERENCES `catastro_db`.`h6m_persona` (`PerDNI`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Relación reflexiva Persona-Cabeza de Familia – reemplaza FK directa en H6M_PERSONA';


-- -----------------------------------------------------
-- Table `catastro_db`.`h7m_familia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`h7m_familia` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`h7m_familia` (
  `FamCod` INT NOT NULL AUTO_INCREMENT COMMENT 'Código Familia – PK (N,8)',
  `FamCab` INT NOT NULL COMMENT 'Cabeza de Familia [FK → H6M_PERSONA]',
  `FamNom` VARCHAR(60) NOT NULL COMMENT 'Apellido/denominación familiar (A,60)',
  `FamViv` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Vivienda del grupo [FK → C3M_VIVIENDA] NULL=sin asignar',
  `FamNumMiem` SMALLINT NOT NULL DEFAULT '1' COMMENT 'Número de miembros (>0)',
  `FamEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`FamCod`),
  INDEX `IDX_FAM_cab` (`FamCab` ASC) VISIBLE,
  INDEX `IDX_FAM_viv` (`FamViv` ASC) VISIBLE,
  CONSTRAINT `FK_FAM_CAB`
    FOREIGN KEY (`FamCab`)
    REFERENCES `catastro_db`.`h6m_persona` (`PerDNI`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_FAM_VIV`
    FOREIGN KEY (`FamViv`)
    REFERENCES `catastro_db`.`c3m_vivienda` (`VivCod`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Maestro Familia – FamViv nullable para carga masiva';


-- -----------------------------------------------------
-- Table `catastro_db`.`p9m_escala_tributo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`p9m_escala_tributo` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`p9m_escala_tributo` (
  `EscCod` VARCHAR(4) NOT NULL COMMENT 'Código escala (A,4) Ej: E01',
  `EscVig` YEAR NOT NULL COMMENT 'Año de vigencia (>2000) – PK2',
  `EscNom` VARCHAR(40) NOT NULL COMMENT 'Nombre descriptivo (A,40)',
  `EscDesc` VARCHAR(200) NULL DEFAULT NULL COMMENT 'Criterio de clasificación (A,200)',
  `EscIngMin` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Límite inferior de ingreso mensual S/ (>=0)',
  `EscIngMax` DECIMAL(10,2) NOT NULL COMMENT 'Límite superior de ingreso mensual S/ (>Min)',
  `EscPorTrib` DECIMAL(5,2) NULL DEFAULT NULL COMMENT '% del valor catastral – exclusivo con EscMonFij',
  `EscMonFij` DECIMAL(10,2) NULL DEFAULT NULL COMMENT 'Monto fijo anual S/ – exclusivo con EscPorTrib',
  `EscEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`EscCod`, `EscVig`),
  INDEX `IDX_ESC_cod` (`EscCod` ASC) VISIBLE,
  INDEX `IDX_ESC_vig` (`EscVig` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Escala Tributaria – PK (EscCod+EscVig) para versionado anual';


-- -----------------------------------------------------
-- Table `catastro_db`.`h8m_propietario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`h8m_propietario` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`h8m_propietario` (
  `ProCod` INT NOT NULL AUTO_INCREMENT COMMENT 'Código Propietario – PK (N,8)',
  `ProPer` INT NOT NULL COMMENT 'Persona [FK → H6M_PERSONA]',
  `ProViv` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Vivienda principal [FK → C3M_VIVIENDA] NULL=sin asignar',
  `ProEscCod` VARCHAR(4) NULL DEFAULT NULL COMMENT 'Código escala [FK → P9M_ESCALA_TRIBUTO] (A,4)',
  `ProEscVig` YEAR NULL DEFAULT NULL COMMENT 'Año vigencia escala [FK → P9M_ESCALA_TRIBUTO]',
  `ProFecCla` DATE NULL DEFAULT NULL COMMENT 'Fecha de clasificación de escala',
  `ProEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`ProCod`),
  INDEX `IDX_PROP_per` (`ProPer` ASC) VISIBLE,
  INDEX `IDX_PROP_viv` (`ProViv` ASC) VISIBLE,
  INDEX `IDX_PROP_esc` (`ProEscCod` ASC, `ProEscVig` ASC) VISIBLE,
  CONSTRAINT `FK_PROP_ESC`
    FOREIGN KEY (`ProEscCod` , `ProEscVig`)
    REFERENCES `catastro_db`.`p9m_escala_tributo` (`EscCod` , `EscVig`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_PROP_PER`
    FOREIGN KEY (`ProPer`)
    REFERENCES `catastro_db`.`h6m_persona` (`PerDNI`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_PROP_VIV`
    FOREIGN KEY (`ProViv`)
    REFERENCES `catastro_db`.`c3m_vivienda` (`VivCod`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Maestro Propietario – ProViv nullable para carga masiva';


-- -----------------------------------------------------
-- Table `catastro_db`.`h8m_prop_vivienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`h8m_prop_vivienda` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`h8m_prop_vivienda` (
  `PvPrp` INT NOT NULL COMMENT 'Propietario [FK → H8M_PROPIETARIO] (PK1)',
  `PvViv` VARCHAR(10) NOT NULL COMMENT 'Vivienda [FK → C3M_VIVIENDA] (PK2)',
  `PvFecIni` DATE NOT NULL COMMENT 'Fecha inicio de propiedad (PK3)',
  `PvFecFin` DATE NULL DEFAULT NULL COMMENT 'Fecha fin – NULL si sigue activo',
  `PvTitulo` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Nº Título de propiedad (A,20)',
  `PvEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`PvPrp`, `PvViv`, `PvFecIni`),
  INDEX `IDX_PV_viv` (`PvViv` ASC) VISIBLE,
  INDEX `IDX_PV_activo` (`PvEstReg` ASC, `PvFecFin` ASC) VISIBLE,
  CONSTRAINT `FK_PV_PROP`
    FOREIGN KEY (`PvPrp`)
    REFERENCES `catastro_db`.`h8m_propietario` (`ProCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_PV_VIV`
    FOREIGN KEY (`PvViv`)
    REFERENCES `catastro_db`.`c3m_vivienda` (`VivCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Asociativa Propietario-Vivienda – PK incluye FecIni para historial de propiedad';


-- -----------------------------------------------------
-- Table `catastro_db`.`pat_tributo_cab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`pat_tributo_cab` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`pat_tributo_cab` (
  `TriCod` INT NOT NULL AUTO_INCREMENT COMMENT 'Código Tributo – PK (N,6)',
  `TriPro` INT NOT NULL COMMENT 'Propietario [FK → H8M_PROPIETARIO]',
  `TriAnio` YEAR NOT NULL COMMENT 'Año del tributo (>2000)',
  `TriMonCal` DECIMAL(14,2) NULL DEFAULT '0.00' COMMENT 'Monto calculado S/',
  `TriMonPag` DECIMAL(14,2) NULL DEFAULT '0.00' COMMENT 'Monto pagado S/',
  `TriFecVen` DATE NULL DEFAULT NULL COMMENT 'Fecha de vencimiento',
  `TriFecPag` DATE NULL DEFAULT NULL COMMENT 'Fecha de pago',
  `TriObs` VARCHAR(200) NULL DEFAULT NULL COMMENT 'Observaciones (A,200)',
  `TriEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro [0=pagado]',
  PRIMARY KEY (`TriCod`),
  UNIQUE INDEX `UQ_TRI_PRO_ANIO` (`TriPro` ASC, `TriAnio` ASC) VISIBLE,
  INDEX `IDX_TRI_pro` (`TriPro` ASC) VISIBLE,
  INDEX `IDX_TRI_anio` (`TriAnio` ASC) VISIBLE,
  INDEX `IDX_TRI_est` (`TriEstReg` ASC, `TriAnio` ASC) VISIBLE,
  CONSTRAINT `FK_TRI_PROP`
    FOREIGN KEY (`TriPro`)
    REFERENCES `catastro_db`.`h8m_propietario` (`ProCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Tributo Cabecera – UNIQUE (TriPro+TriAnio) previene duplicados en carga masiva';


-- -----------------------------------------------------
-- Table `catastro_db`.`pam_historial_tributario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`pam_historial_tributario` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`pam_historial_tributario` (
  `HisCod` INT NOT NULL AUTO_INCREMENT COMMENT 'Código Historial – PK (N,8)',
  `HisTri` INT NOT NULL COMMENT 'Tributo archivado [FK → PAT_TRIBUTO_CAB]',
  `HisAnio` YEAR NOT NULL COMMENT 'Año del tributo (>2000)',
  `HisMonCal` DECIMAL(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Monto calculado al archivar S/',
  `HisMonPag` DECIMAL(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Monto pagado al archivar S/',
  `HisFecPag` DATE NULL DEFAULT NULL COMMENT 'Fecha de pago definitivo',
  `HisFecArch` DATE NOT NULL COMMENT 'Fecha de archivado',
  `HisObs` VARCHAR(200) NULL DEFAULT NULL COMMENT 'Observaciones (A,200)',
  `HisEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`HisCod`),
  INDEX `IDX_HIS_tri` (`HisTri` ASC) VISIBLE,
  INDEX `IDX_HIS_anio` (`HisAnio` ASC) VISIBLE,
  INDEX `IDX_HIS_arch` (`HisFecArch` ASC) VISIBLE,
  CONSTRAINT `FK_HIS_TRI`
    FOREIGN KEY (`HisTri`)
    REFERENCES `catastro_db`.`pat_tributo_cab` (`TriCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Historial Tributario – snapshot de tributos pagados/archivados';


-- -----------------------------------------------------
-- Table `catastro_db`.`pat_tributo_det`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`pat_tributo_det` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`pat_tributo_det` (
  `TriDetCod` INT NOT NULL AUTO_INCREMENT COMMENT 'Código Detalle – PK (N,8)',
  `TriCod` INT NOT NULL COMMENT 'Tributo Cabecera [FK → PAT_TRIBUTO_CAB]',
  `TriDetViv` VARCHAR(10) NOT NULL COMMENT 'Predio del detalle [FK → C3M_VIVIENDA]',
  `TriDetMon` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Monto tributo del predio S/',
  `TriDetEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`TriDetCod`),
  INDEX `IDX_TRIDET_cab` (`TriCod` ASC) VISIBLE,
  INDEX `IDX_TRIDET_viv` (`TriDetViv` ASC) VISIBLE,
  CONSTRAINT `FK_TRIDET_CAB`
    FOREIGN KEY (`TriCod`)
    REFERENCES `catastro_db`.`pat_tributo_cab` (`TriCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_TRIDET_VIV`
    FOREIGN KEY (`TriDetViv`)
    REFERENCES `catastro_db`.`c3m_vivienda` (`VivCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Tributo Detalle – una línea por predio del tributo';


-- -----------------------------------------------------
-- Table `catastro_db`.`pbm_presupuesto_anual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`pbm_presupuesto_anual` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`pbm_presupuesto_anual` (
  `PreCod` INT NOT NULL AUTO_INCREMENT COMMENT 'Código Presupuesto – PK (N,8)',
  `PreMun` INT NOT NULL COMMENT 'Municipalidad [FK → C1M_MUNICIPALIDAD]',
  `PreAnio` YEAR NOT NULL COMMENT 'Año presupuestal (>2000)',
  `PreMonEst` DECIMAL(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Proyección de ingresos por tributos S/ (>0)',
  `PreMonPag` DECIMAL(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Total efectivamente recaudado S/ (>=0)',
  `PreMonGas` DECIMAL(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Total de gastos aprobados S/ (>=0)',
  `PreFecApr` DATE NULL DEFAULT NULL COMMENT 'Fecha de aprobación del presupuesto',
  `PreEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`PreCod`),
  UNIQUE INDEX `UQ_PRE_MUN_ANIO` (`PreMun` ASC, `PreAnio` ASC) VISIBLE,
  INDEX `IDX_PRE_mun` (`PreMun` ASC) VISIBLE,
  INDEX `IDX_PRE_anio` (`PreAnio` ASC) VISIBLE,
  INDEX `IDX_PRE_mun_anio` (`PreMun` ASC, `PreAnio` ASC) VISIBLE,
  CONSTRAINT `FK_PRE_MUN`
    FOREIGN KEY (`PreMun`)
    REFERENCES `catastro_db`.`c1m_municipalidad` (`MunCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Maestro Presupuesto Anual – uno por municipio/año';


-- -----------------------------------------------------
-- Table `catastro_db`.`pbm_tributo_presupuesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`pbm_tributo_presupuesto` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`pbm_tributo_presupuesto` (
  `TpPre` INT NOT NULL COMMENT 'Presupuesto [FK → PBM_PRESUPUESTO_ANUAL] (PK1)',
  `TpTri` INT NOT NULL COMMENT 'Tributo [FK → PAT_TRIBUTO_CAB] (PK2)',
  `TpMonAporte` DECIMAL(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Monto aportado al presupuesto S/ (>=0)',
  `TpFecReg` DATE NOT NULL COMMENT 'Fecha de vinculación al presupuesto',
  `TpEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`TpPre`, `TpTri`),
  INDEX `IDX_TP_tri` (`TpTri` ASC) VISIBLE,
  CONSTRAINT `FK_TP_PRE`
    FOREIGN KEY (`TpPre`)
    REFERENCES `catastro_db`.`pbm_presupuesto_anual` (`PreCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_TP_TRI`
    FOREIGN KEY (`TpTri`)
    REFERENCES `catastro_db`.`pat_tributo_cab` (`TriCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Intermedia Tributo-Presupuesto – qué tributos componen cada presupuesto anual';


-- -----------------------------------------------------
-- Table `catastro_db`.`pcm_reportes_pre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`pcm_reportes_pre` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`pcm_reportes_pre` (
  `RepCod` INT NOT NULL AUTO_INCREMENT COMMENT 'Código Reporte Maestro – PK (N,8)',
  `RepMun` INT NOT NULL COMMENT 'Municipalidad [FK → C1M_MUNICIPALIDAD]',
  `RepZon` INT NULL DEFAULT NULL COMMENT 'Zona opcional [FK → C2M_ZONA] NULL=todo el municipio',
  `RepTip` VARCHAR(4) NOT NULL COMMENT 'Tipo: RPT1=Tributos RPT2=Presupuesto (A,4)',
  `RepTitulo` VARCHAR(120) NOT NULL COMMENT 'Título descriptivo del reporte (A,120)',
  `RepPer` YEAR NOT NULL COMMENT 'Período/año del reporte (>2000)',
  `RepFecGen` DATE NOT NULL COMMENT 'Fecha de generación',
  `RepEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`RepCod`),
  INDEX `IDX_REP_mun` (`RepMun` ASC) VISIBLE,
  INDEX `IDX_REP_zon` (`RepZon` ASC) VISIBLE,
  INDEX `IDX_REP_tip` (`RepTip` ASC) VISIBLE,
  INDEX `IDX_REP_per` (`RepPer` ASC) VISIBLE,
  CONSTRAINT `FK_REP_MUN`
    FOREIGN KEY (`RepMun`)
    REFERENCES `catastro_db`.`c1m_municipalidad` (`MunCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_REP_ZON`
    FOREIGN KEY (`RepZon`)
    REFERENCES `catastro_db`.`c2m_zona` (`ZonCod`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Maestro Reportes – FK zona SET NULL para reportes a nivel municipio';


-- -----------------------------------------------------
-- Table `catastro_db`.`pct_reportes_cab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`pct_reportes_cab` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`pct_reportes_cab` (
  `RepCabCod` INT NOT NULL AUTO_INCREMENT COMMENT 'Código Reporte Cabecera – PK (N,8)',
  `RepCabRep` INT NOT NULL COMMENT 'Reporte Maestro [FK → PCM_REPORTES_PRE]',
  `RepCabPre` INT NULL DEFAULT NULL COMMENT 'Presupuesto asociado [FK → PBM_PRESUPUESTO_ANUAL]',
  `RepCabFec` DATE NOT NULL COMMENT 'Fecha del reporte cabecera',
  `RepCabTotTri` DECIMAL(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Total tributos del período S/',
  `RepCabTotRec` DECIMAL(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Total recaudado S/',
  `RepCabObs` VARCHAR(200) NULL DEFAULT NULL COMMENT 'Observaciones (A,200)',
  `RepCabEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`RepCabCod`),
  INDEX `IDX_REPCAB_rep` (`RepCabRep` ASC) VISIBLE,
  INDEX `IDX_REPCAB_pre` (`RepCabPre` ASC) VISIBLE,
  CONSTRAINT `FK_REPCAB_PRE`
    FOREIGN KEY (`RepCabPre`)
    REFERENCES `catastro_db`.`pbm_presupuesto_anual` (`PreCod`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_REPCAB_REP`
    FOREIGN KEY (`RepCabRep`)
    REFERENCES `catastro_db`.`pcm_reportes_pre` (`RepCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Reporte Cabecera – resumen por municipio/zona con totales';


-- -----------------------------------------------------
-- Table `catastro_db`.`pch_reportes_cab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`pch_reportes_cab` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`pch_reportes_cab` (
  `HRepCabCod` INT NOT NULL AUTO_INCREMENT COMMENT 'Código Historial Rep.Cab – PK (N,8)',
  `HRepCabOri` INT NOT NULL COMMENT 'Reporte Cabecera original [FK → PCT_REPORTES_CAB]',
  `HRepCabFec` DATE NOT NULL COMMENT 'Fecha del reporte original',
  `HRepCabFecArch` DATE NOT NULL COMMENT 'Fecha de archivado',
  `HRepCabTotTri` DECIMAL(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Total tributos al archivar S/',
  `HRepCabTotRec` DECIMAL(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Total recaudado al archivar S/',
  `HRepCabObs` VARCHAR(200) NULL DEFAULT NULL COMMENT 'Observaciones (A,200)',
  `HRepCabEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`HRepCabCod`),
  INDEX `IDX_HREPCAB_ori` (`HRepCabOri` ASC) VISIBLE,
  INDEX `IDX_HREPCAB_arch` (`HRepCabFecArch` ASC) VISIBLE,
  CONSTRAINT `FK_HREPCAB_ORI`
    FOREIGN KEY (`HRepCabOri`)
    REFERENCES `catastro_db`.`pct_reportes_cab` (`RepCabCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Historial Reporte Cabecera – versiones archivadas con snapshot de montos';


-- -----------------------------------------------------
-- Table `catastro_db`.`pct_reportes_det`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`pct_reportes_det` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`pct_reportes_det` (
  `RepDetCod` INT NOT NULL AUTO_INCREMENT COMMENT 'Código Reporte Detalle – PK (N,8)',
  `RepDetCab` INT NOT NULL COMMENT 'Reporte Cabecera [FK → PCT_REPORTES_CAB]',
  `RepDetProp` INT NULL DEFAULT NULL COMMENT 'Propietario [FK → H8M_PROPIETARIO]',
  `RepDetViv` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Predio [FK → C3M_VIVIENDA]',
  `RepDetTri` INT NULL DEFAULT NULL COMMENT 'Tributo [FK → PAT_TRIBUTO_CAB]',
  `RepDetMonCal` DECIMAL(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Monto calculado S/',
  `RepDetMonPag` DECIMAL(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Monto pagado S/',
  `RepDetEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`RepDetCod`),
  INDEX `IDX_REPDET_cab` (`RepDetCab` ASC) VISIBLE,
  INDEX `IDX_REPDET_prop` (`RepDetProp` ASC) VISIBLE,
  INDEX `IDX_REPDET_viv` (`RepDetViv` ASC) VISIBLE,
  INDEX `IDX_REPDET_tri` (`RepDetTri` ASC) VISIBLE,
  CONSTRAINT `FK_REPDET_CAB`
    FOREIGN KEY (`RepDetCab`)
    REFERENCES `catastro_db`.`pct_reportes_cab` (`RepCabCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_REPDET_PROP`
    FOREIGN KEY (`RepDetProp`)
    REFERENCES `catastro_db`.`h8m_propietario` (`ProCod`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_REPDET_TRI`
    FOREIGN KEY (`RepDetTri`)
    REFERENCES `catastro_db`.`pat_tributo_cab` (`TriCod`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_REPDET_VIV`
    FOREIGN KEY (`RepDetViv`)
    REFERENCES `catastro_db`.`c3m_vivienda` (`VivCod`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Reporte Detalle – una línea por propietario/predio/tributo';


-- -----------------------------------------------------
-- Table `catastro_db`.`pch_reportes_det`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro_db`.`pch_reportes_det` ;

CREATE TABLE IF NOT EXISTS `catastro_db`.`pch_reportes_det` (
  `HRepDetCod` INT NOT NULL AUTO_INCREMENT COMMENT 'Código Historial Rep.Det – PK (N,8)',
  `HRepDetCab` INT NOT NULL COMMENT 'Historial Rep.Cab [FK → PCH_REPORTES_CAB]',
  `HRepDetOri` INT NULL DEFAULT NULL COMMENT 'Detalle original [FK → PCT_REPORTES_DET]',
  `HRepDetMonCal` DECIMAL(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Monto calculado al archivar S/',
  `HRepDetMonPag` DECIMAL(14,2) NOT NULL DEFAULT '0.00' COMMENT 'Monto pagado al archivar S/',
  `HRepDetEstReg` CHAR(1) NOT NULL DEFAULT '1' COMMENT 'Estado registro',
  PRIMARY KEY (`HRepDetCod`),
  INDEX `IDX_HREPDET_cab` (`HRepDetCab` ASC) VISIBLE,
  INDEX `IDX_HREPDET_ori` (`HRepDetOri` ASC) VISIBLE,
  CONSTRAINT `FK_HREPDET_CAB`
    FOREIGN KEY (`HRepDetCab`)
    REFERENCES `catastro_db`.`pch_reportes_cab` (`HRepCabCod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_HREPDET_ORI`
    FOREIGN KEY (`HRepDetOri`)
    REFERENCES `catastro_db`.`pct_reportes_det` (`RepDetCod`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci
COMMENT = 'Historial Reporte Detalle – líneas archivadas con snapshot de montos';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
