-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.c1m_distrito
(
    discod integer NOT NULL,
    dispro integer NOT NULL,
    disnom character varying(60) COLLATE pg_catalog."default" NOT NULL,
    disestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_c1m_distrito PRIMARY KEY (discod)
);

CREATE TABLE IF NOT EXISTS public.c1m_municipalidad
(
    muncod serial NOT NULL,
    mundis integer NOT NULL,
    munnom character varying(60) COLLATE pg_catalog."default" NOT NULL,
    munalcnom character varying(120) COLLATE pg_catalog."default",
    muncor character varying(80) COLLATE pg_catalog."default",
    muntelcon character varying(15) COLLATE pg_catalog."default",
    munestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_c1m_municipalidad PRIMARY KEY (muncod)
);

CREATE TABLE IF NOT EXISTS public.c1m_provincia
(
    procod integer NOT NULL,
    proreg integer NOT NULL,
    pronom character varying(60) COLLATE pg_catalog."default" NOT NULL,
    proestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_c1m_provincia PRIMARY KEY (procod)
);

CREATE TABLE IF NOT EXISTS public.c1m_region
(
    regcod serial NOT NULL,
    regnom character varying(60) COLLATE pg_catalog."default" NOT NULL,
    regestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,
    CONSTRAINT pk_c1m_region PRIMARY KEY (regcod)
);

CREATE TABLE IF NOT EXISTS public.c2m_zona
(
    zoncod serial NOT NULL,
    zonmun integer NOT NULL,
    zonnom character varying(60) COLLATE pg_catalog."default" NOT NULL,
    zondes character varying(100) COLLATE pg_catalog."default",
    zontip character(1) COLLATE pg_catalog."default" NOT NULL,
    zonsupkm2 numeric(10, 2),
    zonestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_c2m_zona PRIMARY KEY (zoncod)
);

CREATE TABLE IF NOT EXISTS public.c3m_bloque_casas
(
    blovivcod character varying(10) COLLATE pg_catalog."default" NOT NULL,
    blometb numeric(8, 2) NOT NULL,
    blood character varying(200) COLLATE pg_catalog."default",
    bloestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_c3m_bloque_casas PRIMARY KEY (blovivcod)
);

CREATE TABLE IF NOT EXISTS public.c3m_casa_particular
(
    casvivcod character varying(10) COLLATE pg_catalog."default" NOT NULL,
    casmetc numeric(8, 2) NOT NULL,
    casod character varying(200) COLLATE pg_catalog."default",
    casestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_c3m_casa_particular PRIMARY KEY (casvivcod)
);

CREATE TABLE IF NOT EXISTS public.c3m_direccion
(
    dircod serial NOT NULL,
    dirzon integer NOT NULL,
    dirviatip character varying(4) COLLATE pg_catalog."default" NOT NULL,
    dirvianom character varying(80) COLLATE pg_catalog."default" NOT NULL,
    dirnum character varying(10) COLLATE pg_catalog."default",
    dirint character varying(10) COLLATE pg_catalog."default",
    dirurb character varying(80) COLLATE pg_catalog."default",
    dirref character varying(120) COLLATE pg_catalog."default",
    dircodpos character varying(5) COLLATE pg_catalog."default",
    dirlat numeric(10, 7),
    dirlon numeric(10, 7),
    direstreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_c3m_direccion PRIMARY KEY (dircod)
);

CREATE TABLE IF NOT EXISTS public.c3m_partida_registral
(
    prtcod serial NOT NULL,
    prtviv character varying(10) COLLATE pg_catalog."default" NOT NULL,
    prtzonreg character varying(6) COLLATE pg_catalog."default" NOT NULL,
    prtnumpartida character varying(12) COLLATE pg_catalog."default" NOT NULL,
    prtfoliotomo character varying(10) COLLATE pg_catalog."default",
    prtfoliofolio character varying(10) COLLATE pg_catalog."default",
    prtasiento character varying(10) COLLATE pg_catalog."default",
    prttipoacto character varying(40) COLLATE pg_catalog."default" NOT NULL,
    prtpropnom character varying(200) COLLATE pg_catalog."default",
    prtpropdni character varying(12) COLLATE pg_catalog."default",
    prtest character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT 'A'::bpchar,
    prtfecins date NOT NULL,
    prtfecultact date,
    prtaream2 numeric(10, 2),
    prtobs character varying(200) COLLATE pg_catalog."default",
    prtestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,
    CONSTRAINT pk_c3m_partida_registral PRIMARY KEY (prtcod)
);

CREATE TABLE IF NOT EXISTS public.c3m_via_tipo
(
    vtcod character varying(4) COLLATE pg_catalog."default" NOT NULL,
    vtnom character varying(40) COLLATE pg_catalog."default" NOT NULL,
    vtestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,
    CONSTRAINT pk_c3m_via_tipo PRIMARY KEY (vtcod)
);

CREATE TABLE IF NOT EXISTS public.c3m_vivienda
(
    vivcod character varying(10) COLLATE pg_catalog."default" NOT NULL,
    vivzon integer NOT NULL,
    vivdir integer,
    vivubigeo character varying(15) COLLATE pg_catalog."default",
    vivtippr character varying(4) COLLATE pg_catalog."default",
    vivusopr character varying(4) COLLATE pg_catalog."default",
    vivval numeric(10, 2) NOT NULL DEFAULT 0.00,
    vivestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_c3m_vivienda PRIMARY KEY (vivcod)
);

CREATE TABLE IF NOT EXISTS public.c4m_departamento
(
    depblocod character varying(10) COLLATE pg_catalog."default" NOT NULL,
    depesc character varying(4) COLLATE pg_catalog."default" NOT NULL,
    depniv smallint NOT NULL DEFAULT 0,
    deppue character varying(4) COLLATE pg_catalog."default" NOT NULL,
    depmetp numeric(6, 2) NOT NULL,
    depod character varying(200) COLLATE pg_catalog."default",
    depestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_c4m_departamento PRIMARY KEY (depblocod, depesc, depniv, deppue)
);

CREATE TABLE IF NOT EXISTS public.c5m_tipo_predio
(
    tipprcod character varying(4) COLLATE pg_catalog."default" NOT NULL,
    tipprnom character varying(60) COLLATE pg_catalog."default" NOT NULL,
    tipprdes character varying(200) COLLATE pg_catalog."default",
    tipprestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_c5m_tipo_predio PRIMARY KEY (tipprcod)
);

CREATE TABLE IF NOT EXISTS public.c5m_uso_predio
(
    usoprcod character varying(4) COLLATE pg_catalog."default" NOT NULL,
    usoprnom character varying(60) COLLATE pg_catalog."default" NOT NULL,
    usoprdes character varying(200) COLLATE pg_catalog."default",
    usoprestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_c5m_uso_predio PRIMARY KEY (usoprcod)
);

CREATE TABLE IF NOT EXISTS public.c5m_valor_catastral
(
    valcod serial NOT NULL,
    valviv character varying(10) COLLATE pg_catalog."default" NOT NULL,
    valanio smallint NOT NULL,
    valmon numeric(14, 2) NOT NULL,
    valfecreg date NOT NULL,
    valfecmod date,
    valestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_c5m_valor_catastral PRIMARY KEY (valcod)
);

CREATE TABLE IF NOT EXISTS public.h6m_cab_familia
(
    cabdni integer NOT NULL,
    miedni integer NOT NULL,
    cabfecini date NOT NULL,
    cabfecfin date,
    cabestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_h6m_cab_familia PRIMARY KEY (cabdni, miedni)
);

CREATE TABLE IF NOT EXISTS public.h6m_persona
(
    perdni integer NOT NULL,
    pernom character varying(60) COLLATE pg_catalog."default" NOT NULL,
    perapepat character varying(60) COLLATE pg_catalog."default" NOT NULL,
    perapemat character varying(60) COLLATE pg_catalog."default" NOT NULL,
    pering numeric(10, 2) NOT NULL DEFAULT 0.00,
    perviv character varying(10) COLLATE pg_catalog."default",
    perestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_h6m_persona PRIMARY KEY (perdni)
);

CREATE TABLE IF NOT EXISTS public.h7m_familia
(
    famcod serial NOT NULL,
    famcab integer NOT NULL,
    famnom character varying(60) COLLATE pg_catalog."default" NOT NULL,
    famviv character varying(10) COLLATE pg_catalog."default",
    famnummiem smallint NOT NULL DEFAULT 1,
    famestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_h7m_familia PRIMARY KEY (famcod)
);

CREATE TABLE IF NOT EXISTS public.h8m_prop_vivienda
(
    pvprp integer NOT NULL,
    pvviv character varying(10) COLLATE pg_catalog."default" NOT NULL,
    pvfecini date NOT NULL,
    pvfecfin date,
    pvtitulo character varying(20) COLLATE pg_catalog."default",
    pvestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_h8m_prop_vivienda PRIMARY KEY (pvprp, pvviv, pvfecini)
);

CREATE TABLE IF NOT EXISTS public.h8m_propietario
(
    procod serial NOT NULL,
    proper integer NOT NULL,
    proviv character varying(10) COLLATE pg_catalog."default",
    proesccod character varying(4) COLLATE pg_catalog."default",
    proescvig smallint,
    profeccla date,
    proestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_h8m_propietario PRIMARY KEY (procod)
);

CREATE TABLE IF NOT EXISTS public.p9m_escala_tributo
(
    esccod character varying(4) COLLATE pg_catalog."default" NOT NULL,
    escvig smallint NOT NULL,
    escnom character varying(40) COLLATE pg_catalog."default" NOT NULL,
    escdesc character varying(200) COLLATE pg_catalog."default",
    escingmin numeric(10, 2) NOT NULL DEFAULT 0.00,
    escingmax numeric(10, 2) NOT NULL,
    escportrib numeric(5, 2),
    escmonfij numeric(10, 2),
    escestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_p9m_escala_tributo PRIMARY KEY (esccod, escvig)
);

CREATE TABLE IF NOT EXISTS public.pam_historial_tributario
(
    hiscod serial NOT NULL,
    histri integer NOT NULL,
    hisanio smallint NOT NULL,
    hismoncal numeric(14, 2) NOT NULL DEFAULT 0.00,
    hismonpag numeric(14, 2) NOT NULL DEFAULT 0.00,
    hisfecpag date,
    hisfecarch date NOT NULL,
    hisobs character varying(200) COLLATE pg_catalog."default",
    hisestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_pam_historial_tributario PRIMARY KEY (hiscod)
);

CREATE TABLE IF NOT EXISTS public.pat_tributo_cab
(
    tricod serial NOT NULL,
    tripro integer NOT NULL,
    trianio smallint NOT NULL,
    trimoncal numeric(14, 2) DEFAULT 0.00,
    trimonpag numeric(14, 2) DEFAULT 0.00,
    trifecven date,
    trifecpag date,
    triobs character varying(200) COLLATE pg_catalog."default",
    triestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_pat_tributo_cab PRIMARY KEY (tricod)
);

CREATE TABLE IF NOT EXISTS public.pat_tributo_det
(
    tridetcod serial NOT NULL,
    tricod integer NOT NULL,
    tridetviv character varying(10) COLLATE pg_catalog."default" NOT NULL,
    tridetmon numeric(10, 2) NOT NULL DEFAULT 0.00,
    tridetestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_pat_tributo_det PRIMARY KEY (tridetcod)
);

CREATE TABLE IF NOT EXISTS public.pbm_presupuesto_anual
(
    precod serial NOT NULL,
    premun integer NOT NULL,
    preanio smallint NOT NULL,
    premonest numeric(14, 2) NOT NULL DEFAULT 0.00,
    premonpag numeric(14, 2) NOT NULL DEFAULT 0.00,
    premongas numeric(14, 2) NOT NULL DEFAULT 0.00,
    prefecapr date,
    preestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_pbm_presupuesto_anual PRIMARY KEY (precod)
);

CREATE TABLE IF NOT EXISTS public.pbm_tributo_presupuesto
(
    tppre integer NOT NULL,
    tptri integer NOT NULL,
    tpmonaporte numeric(14, 2) NOT NULL DEFAULT 0.00,
    tpfecreg date NOT NULL,
    tpestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_pbm_tributo_presupuesto PRIMARY KEY (tppre, tptri)
);

CREATE TABLE IF NOT EXISTS public.pch_reportes_cab
(
    hrepcabcod serial NOT NULL,
    hrepcabori integer NOT NULL,
    hrepcabfec date NOT NULL,
    hrepcabfecarch date NOT NULL,
    hrepcabtottri numeric(14, 2) NOT NULL DEFAULT 0.00,
    hrepcabtotrec numeric(14, 2) NOT NULL DEFAULT 0.00,
    hrepcabobs character varying(200) COLLATE pg_catalog."default",
    hrepcabestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_pch_reportes_cab PRIMARY KEY (hrepcabcod)
);

CREATE TABLE IF NOT EXISTS public.pch_reportes_det
(
    hrepdetcod serial NOT NULL,
    hrepdetcab integer NOT NULL,
    hrepdetori integer,
    hrepdetmoncal numeric(14, 2) NOT NULL DEFAULT 0.00,
    hrepdetmonpag numeric(14, 2) NOT NULL DEFAULT 0.00,
    hrepdetestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_pch_reportes_det PRIMARY KEY (hrepdetcod)
);

CREATE TABLE IF NOT EXISTS public.pcm_reportes_pre
(
    repcod serial NOT NULL,
    repmun integer NOT NULL,
    repzon integer,
    reptip character varying(4) COLLATE pg_catalog."default" NOT NULL,
    reptitulo character varying(120) COLLATE pg_catalog."default" NOT NULL,
    repper smallint NOT NULL,
    repfecgen date NOT NULL,
    repestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_pcm_reportes_pre PRIMARY KEY (repcod)
);

CREATE TABLE IF NOT EXISTS public.pct_reportes_cab
(
    repcabcod serial NOT NULL,
    repcabrep integer NOT NULL,
    repcabpre integer,
    repcabfec date NOT NULL,
    repcabtottri numeric(14, 2) NOT NULL DEFAULT 0.00,
    repcabtotrec numeric(14, 2) NOT NULL DEFAULT 0.00,
    repcabobs character varying(200) COLLATE pg_catalog."default",
    repcabestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_pct_reportes_cab PRIMARY KEY (repcabcod)
);

CREATE TABLE IF NOT EXISTS public.pct_reportes_det
(
    repdetcod serial NOT NULL,
    repdetcab integer NOT NULL,
    repdetprop integer,
    repdetviv character varying(10) COLLATE pg_catalog."default",
    repdettri integer,
    repdetmoncal numeric(14, 2) NOT NULL DEFAULT 0.00,
    repdetmonpag numeric(14, 2) NOT NULL DEFAULT 0.00,
    repdetestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

    CONSTRAINT pk_pct_reportes_det PRIMARY KEY (repdetcod)
);

CREATE TABLE IF NOT EXISTS public.vw_predio_detallado
(
    codigo_predio character varying(10) COLLATE pg_catalog."default" NOT NULL,
    valor_predio numeric(10, 2) NOT NULL DEFAULT 0.00,
    ubigeo character varying(15) COLLATE pg_catalog."default",
    tipo_predio character varying(60) COLLATE pg_catalog."default",
    uso_predio character varying(60) COLLATE pg_catalog."default",
    direccion character varying(132) COLLATE pg_catalog."default",
    urbanizacion character varying(80) COLLATE pg_catalog."default",
    zona character varying(60) COLLATE pg_catalog."default" NOT NULL,
    tipo_zona character(1) COLLATE pg_catalog."default" NOT NULL,
    municipalidad character varying(60) COLLATE pg_catalog."default" NOT NULL,
    alcalde character varying(120) COLLATE pg_catalog."default",
    distrito character varying(60) COLLATE pg_catalog."default" NOT NULL,
    provincia character varying(60) COLLATE pg_catalog."default" NOT NULL,
    region character varying(60) COLLATE pg_catalog."default" NOT NULL,
    estado_predio character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

);

CREATE TABLE IF NOT EXISTS public.vw_propietario_persona
(
    procod integer NOT NULL DEFAULT 0,
    perdni integer NOT NULL,
    nombre_completo character varying(182) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    ingreso_mensual numeric(10, 2) NOT NULL DEFAULT 0.00,
    predio_principal character varying(10) COLLATE pg_catalog."default",
    proesccod character varying(4) COLLATE pg_catalog."default",
    proescvig smallint,
    proestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

);

CREATE TABLE IF NOT EXISTS public.vw_vivienda_completa
(
    vivcod character varying(10) COLLATE pg_catalog."default" NOT NULL,
    vivval numeric(10, 2) NOT NULL DEFAULT 0.00,
    vivubigeo character varying(15) COLLATE pg_catalog."default",
    tipo_predio character varying(60) COLLATE pg_catalog."default",
    tipo_predio_desc character varying(200) COLLATE pg_catalog."default",
    uso_predio character varying(60) COLLATE pg_catalog."default",
    uso_predio_desc character varying(200) COLLATE pg_catalog."default",
    vivestreg character(1) COLLATE pg_catalog."default" NOT NULL DEFAULT '1'::bpchar,

);

ALTER TABLE IF EXISTS public.c1m_distrito
    ADD CONSTRAINT fk_dis_pro FOREIGN KEY (dispro)
    REFERENCES public.c1m_provincia (procod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_dis_pro
    ON public.c1m_distrito(dispro);


ALTER TABLE IF EXISTS public.c1m_municipalidad
    ADD CONSTRAINT fk_mun_dis FOREIGN KEY (mundis)
    REFERENCES public.c1m_distrito (discod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_mun_dis
    ON public.c1m_municipalidad(mundis);


ALTER TABLE IF EXISTS public.c1m_provincia
    ADD CONSTRAINT fk_pro_reg FOREIGN KEY (proreg)
    REFERENCES public.c1m_region (regcod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_pro_reg
    ON public.c1m_provincia(proreg);


ALTER TABLE IF EXISTS public.c2m_zona
    ADD CONSTRAINT fk_zon_mun FOREIGN KEY (zonmun)
    REFERENCES public.c1m_municipalidad (muncod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_zon_mun
    ON public.c2m_zona(zonmun);


ALTER TABLE IF EXISTS public.c3m_bloque_casas
    ADD CONSTRAINT fk_blo_viv FOREIGN KEY (blovivcod)
    REFERENCES public.c3m_vivienda (vivcod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS pk_c3m_bloque_casas
    ON public.c3m_bloque_casas(blovivcod);


ALTER TABLE IF EXISTS public.c3m_casa_particular
    ADD CONSTRAINT fk_cas_viv FOREIGN KEY (casvivcod)
    REFERENCES public.c3m_vivienda (vivcod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS pk_c3m_casa_particular
    ON public.c3m_casa_particular(casvivcod);


ALTER TABLE IF EXISTS public.c3m_direccion
    ADD CONSTRAINT fk_dir_viatip FOREIGN KEY (dirviatip)
    REFERENCES public.c3m_via_tipo (vtcod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.c3m_direccion
    ADD CONSTRAINT fk_dir_zon FOREIGN KEY (dirzon)
    REFERENCES public.c2m_zona (zoncod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_dir_zon
    ON public.c3m_direccion(dirzon);


ALTER TABLE IF EXISTS public.c3m_partida_registral
    ADD CONSTRAINT fk_prt_viv FOREIGN KEY (prtviv)
    REFERENCES public.c3m_vivienda (vivcod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_prt_viv
    ON public.c3m_partida_registral(prtviv);


ALTER TABLE IF EXISTS public.c3m_vivienda
    ADD CONSTRAINT fk_viv_dir FOREIGN KEY (vivdir)
    REFERENCES public.c3m_direccion (dircod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_viv_dir
    ON public.c3m_vivienda(vivdir);


ALTER TABLE IF EXISTS public.c3m_vivienda
    ADD CONSTRAINT fk_viv_tippr FOREIGN KEY (vivtippr)
    REFERENCES public.c5m_tipo_predio (tipprcod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_viv_tippr
    ON public.c3m_vivienda(vivtippr);


ALTER TABLE IF EXISTS public.c3m_vivienda
    ADD CONSTRAINT fk_viv_usopr FOREIGN KEY (vivusopr)
    REFERENCES public.c5m_uso_predio (usoprcod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_viv_usopr
    ON public.c3m_vivienda(vivusopr);


ALTER TABLE IF EXISTS public.c3m_vivienda
    ADD CONSTRAINT fk_viv_zon FOREIGN KEY (vivzon)
    REFERENCES public.c2m_zona (zoncod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_viv_zon
    ON public.c3m_vivienda(vivzon);


ALTER TABLE IF EXISTS public.c4m_departamento
    ADD CONSTRAINT fk_dep_blo FOREIGN KEY (depblocod)
    REFERENCES public.c3m_bloque_casas (blovivcod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_dep_bloque
    ON public.c4m_departamento(depblocod);


ALTER TABLE IF EXISTS public.c5m_valor_catastral
    ADD CONSTRAINT fk_val_viv FOREIGN KEY (valviv)
    REFERENCES public.c3m_vivienda (vivcod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_val_viv
    ON public.c5m_valor_catastral(valviv);


ALTER TABLE IF EXISTS public.h6m_cab_familia
    ADD CONSTRAINT fk_cab_cabeza FOREIGN KEY (cabdni)
    REFERENCES public.h6m_persona (perdni) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.h6m_cab_familia
    ADD CONSTRAINT fk_cab_miembro FOREIGN KEY (miedni)
    REFERENCES public.h6m_persona (perdni) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_cab_miembro
    ON public.h6m_cab_familia(miedni);


ALTER TABLE IF EXISTS public.h6m_persona
    ADD CONSTRAINT fk_per_viv FOREIGN KEY (perviv)
    REFERENCES public.c3m_vivienda (vivcod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_per_viv
    ON public.h6m_persona(perviv);


ALTER TABLE IF EXISTS public.h7m_familia
    ADD CONSTRAINT fk_fam_cab FOREIGN KEY (famcab)
    REFERENCES public.h6m_persona (perdni) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_fam_cab
    ON public.h7m_familia(famcab);


ALTER TABLE IF EXISTS public.h7m_familia
    ADD CONSTRAINT fk_fam_viv FOREIGN KEY (famviv)
    REFERENCES public.c3m_vivienda (vivcod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_fam_viv
    ON public.h7m_familia(famviv);


ALTER TABLE IF EXISTS public.h8m_prop_vivienda
    ADD CONSTRAINT fk_pv_prop FOREIGN KEY (pvprp)
    REFERENCES public.h8m_propietario (procod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.h8m_prop_vivienda
    ADD CONSTRAINT fk_pv_viv FOREIGN KEY (pvviv)
    REFERENCES public.c3m_vivienda (vivcod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_pv_viv
    ON public.h8m_prop_vivienda(pvviv);


ALTER TABLE IF EXISTS public.h8m_propietario
    ADD CONSTRAINT fk_prop_esc FOREIGN KEY (proesccod, proescvig)
    REFERENCES public.p9m_escala_tributo (esccod, escvig) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_prop_esc
    ON public.h8m_propietario(proesccod, proescvig);


ALTER TABLE IF EXISTS public.h8m_propietario
    ADD CONSTRAINT fk_prop_per FOREIGN KEY (proper)
    REFERENCES public.h6m_persona (perdni) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_prop_per
    ON public.h8m_propietario(proper);


ALTER TABLE IF EXISTS public.h8m_propietario
    ADD CONSTRAINT fk_prop_viv FOREIGN KEY (proviv)
    REFERENCES public.c3m_vivienda (vivcod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_prop_viv
    ON public.h8m_propietario(proviv);


ALTER TABLE IF EXISTS public.pam_historial_tributario
    ADD CONSTRAINT fk_his_tri FOREIGN KEY (histri)
    REFERENCES public.pat_tributo_cab (tricod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_his_tri
    ON public.pam_historial_tributario(histri);


ALTER TABLE IF EXISTS public.pat_tributo_cab
    ADD CONSTRAINT fk_tri_prop FOREIGN KEY (tripro)
    REFERENCES public.h8m_propietario (procod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_tri_pro
    ON public.pat_tributo_cab(tripro);


ALTER TABLE IF EXISTS public.pat_tributo_det
    ADD CONSTRAINT fk_tridet_cab FOREIGN KEY (tricod)
    REFERENCES public.pat_tributo_cab (tricod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_tridet_cab
    ON public.pat_tributo_det(tricod);


ALTER TABLE IF EXISTS public.pat_tributo_det
    ADD CONSTRAINT fk_tridet_viv FOREIGN KEY (tridetviv)
    REFERENCES public.c3m_vivienda (vivcod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_tridet_viv
    ON public.pat_tributo_det(tridetviv);


ALTER TABLE IF EXISTS public.pbm_presupuesto_anual
    ADD CONSTRAINT fk_pre_mun FOREIGN KEY (premun)
    REFERENCES public.c1m_municipalidad (muncod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_pre_mun
    ON public.pbm_presupuesto_anual(premun);


ALTER TABLE IF EXISTS public.pbm_tributo_presupuesto
    ADD CONSTRAINT fk_tp_pre FOREIGN KEY (tppre)
    REFERENCES public.pbm_presupuesto_anual (precod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.pbm_tributo_presupuesto
    ADD CONSTRAINT fk_tp_tri FOREIGN KEY (tptri)
    REFERENCES public.pat_tributo_cab (tricod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_tp_tri
    ON public.pbm_tributo_presupuesto(tptri);


ALTER TABLE IF EXISTS public.pch_reportes_cab
    ADD CONSTRAINT fk_hrepcab_ori FOREIGN KEY (hrepcabori)
    REFERENCES public.pct_reportes_cab (repcabcod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_hrepcab_ori
    ON public.pch_reportes_cab(hrepcabori);


ALTER TABLE IF EXISTS public.pch_reportes_det
    ADD CONSTRAINT fk_hrepdet_cab FOREIGN KEY (hrepdetcab)
    REFERENCES public.pch_reportes_cab (hrepcabcod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_hrepdet_cab
    ON public.pch_reportes_det(hrepdetcab);


ALTER TABLE IF EXISTS public.pch_reportes_det
    ADD CONSTRAINT fk_hrepdet_ori FOREIGN KEY (hrepdetori)
    REFERENCES public.pct_reportes_det (repdetcod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_hrepdet_ori
    ON public.pch_reportes_det(hrepdetori);


ALTER TABLE IF EXISTS public.pcm_reportes_pre
    ADD CONSTRAINT fk_rep_mun FOREIGN KEY (repmun)
    REFERENCES public.c1m_municipalidad (muncod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_rep_mun
    ON public.pcm_reportes_pre(repmun);


ALTER TABLE IF EXISTS public.pcm_reportes_pre
    ADD CONSTRAINT fk_rep_zon FOREIGN KEY (repzon)
    REFERENCES public.c2m_zona (zoncod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_rep_zon
    ON public.pcm_reportes_pre(repzon);


ALTER TABLE IF EXISTS public.pct_reportes_cab
    ADD CONSTRAINT fk_repcab_pre FOREIGN KEY (repcabpre)
    REFERENCES public.pbm_presupuesto_anual (precod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_repcab_pre
    ON public.pct_reportes_cab(repcabpre);


ALTER TABLE IF EXISTS public.pct_reportes_cab
    ADD CONSTRAINT fk_repcab_rep FOREIGN KEY (repcabrep)
    REFERENCES public.pcm_reportes_pre (repcod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_repcab_rep
    ON public.pct_reportes_cab(repcabrep);


ALTER TABLE IF EXISTS public.pct_reportes_det
    ADD CONSTRAINT fk_repdet_cab FOREIGN KEY (repdetcab)
    REFERENCES public.pct_reportes_cab (repcabcod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_repdet_cab
    ON public.pct_reportes_det(repdetcab);


ALTER TABLE IF EXISTS public.pct_reportes_det
    ADD CONSTRAINT fk_repdet_prop FOREIGN KEY (repdetprop)
    REFERENCES public.h8m_propietario (procod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_repdet_prop
    ON public.pct_reportes_det(repdetprop);


ALTER TABLE IF EXISTS public.pct_reportes_det
    ADD CONSTRAINT fk_repdet_tri FOREIGN KEY (repdettri)
    REFERENCES public.pat_tributo_cab (tricod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_repdet_tri
    ON public.pct_reportes_det(repdettri);


ALTER TABLE IF EXISTS public.pct_reportes_det
    ADD CONSTRAINT fk_repdet_viv FOREIGN KEY (repdetviv)
    REFERENCES public.c3m_vivienda (vivcod) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_repdet_viv
    ON public.pct_reportes_det(repdetviv);

END;